### PR TITLE
 Deny access to disabled account/domain. Fixes #88

### LINKED ISSUE #88: Behavior disabled domain/accounts
In the testing-procedure, I found this:
https://github.com/vexim/vexim2/blob/master/docs/checklist.txt#L71-L73

Disabled domain -> postmaster can login, user can't (all should be able to login)
Disabled account -> user can login (should fail)

I don't know, where this feature was lost and if there were some security aspects. Do we want this back? @rimas-kudelis

### PR DESCRIPTION
**Pull request by Udera**
Replacing https://github.com/vexim/vexim2/pull/95 to fix https://github.com/vexim/vexim2/issues/88

I put the checks before the session-variable is initialized. Indentation fixes are in a separate commit.

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
Other than the four empty consecutive lines, the patch looks OK to my tired eyes.

However, I wonder what happens if the account or domain becomes deactivated while the user is still logged in. Should we account for that as well?

**Comment by rimas-kudelis** [comment]
Also, it would be better if we didn't replace PR's, but update them instead. To update, you just have to push to the same branch, and if rewriting commit history, you should use `-f` when pushing.

**Comment by Udera** [comment]
I thought about the active sessions. But the point is, once an account/domain is disabled, exim won't handle mails any more and imap-logins are disabled as well. A user could only change some settings that get active once his account his activated again.

I created a new branch because I wanted to keep the previous changes. I could have pushed the changes of my local new branch to the same remote branch on github.

**Comment by Udera** [comment]
I didn't see consecutive empty lines?

I inserted a forced logout for disabled domains/users who are currently logged in.

File: vexim/config/header.php [hunk 1]
```diff
@@ -1,24 +1,25 @@
...
-    $domsuccess = $domheaderresult->execute(array(':domain_id'=>$_SESSION['domain_id']));
-    if ($domsuccess) { $domheaderrow = $domheaderresult->fetch(); }
-    $usrheaderquery = "SELECT enabled FROM users WHERE localpart=:localpart AND domain_id=:domain_id";
-    $usrheaderresult = $dbh->prepare($usrheaderquery);
-    $usrsuccess = $usrheaderresult->execute(array(':localpart'=>$_SESSION['localpart'], ':domain_id'=>$_SESSION['domain_id']));
-    if ($usrsuccess) { $usrheaderrow = $usrheaderresult->fetch(); }
-  }
-
-  print "<div id=\"Header\"><p><a href=\"https://github.com/avleen/vexim2\" target=\"_blank\">" . _("Virtual Exim") . "</a> ";
+  print "<div id=\"Header\"><p><a href=\"https://github.com/vexim/vexim2\" target=\"_blank\">" . _("Virtual Exim") . "</a> ";
```
Comment (rimas-kudelis) [inline vexim/config/header.php]: Why did you put output above `header()` calls?  I don't see why it would matter for the application logic, so it looks like the lines are reshuffled just for the sake of it. Please don't do this.

File: vexim/config/header.php [hunk 2]
```diff
@@ -1,24 +1,25 @@
...
-      print   _("-- account disabled (please see your administrator).");
+  if (isset($_SESSION['domain_id'])) { // Check if accound or domain haven't been disabled
+    $headerquery = "SELECT domains.enabled AS domain, users.enabled AS user FROM users,domains
+                    WHERE users.localpart=:localpart AND domains.domain_id=:domain_id AND users.domain_id=domains.domain_id;";
+    $headerresult = $dbh->prepare($headerquery);
+    $headersuccess = $headerresult->execute(array(':localpart'=>$_SESSION['localpart'], ':domain_id'=>$_SESSION['domain_id']));
+    if ($headersuccess) {
+      $headerrow = $headerresult->fetch();
+      if ($headerrow['domain'] === "0") {
+        unset($_SESSION['domain_id']);
```
Comment (rimas-kudelis) [inline vexim/config/header.php]: I suppose it would be better to do here what `logout.php` does, only the `header()` call should remain different. Perhaps we should even have it always done in a single place, e.g. in `functions.php`?

File: vexim/config/header.php (hunk 1 above)
Comment (Udera) [inline vexim/config/header.php]: Sorry, I wanted to do it differently in the beginning where the order did matter. I'll change it back.

**Comment by Udera** [comment]
I put a new function invalidate_session() into the config/functions.php to close a session. Therefore the logout.php was updated and I put this function into the config/header.php.

File: vexim/config/header.php [hunk 3]
```diff
@@ -1,26 +1,27 @@
...
-    $usrheaderresult = $dbh->prepare($usrheaderquery);
-    $usrsuccess = $usrheaderresult->execute(array(':localpart'=>$_SESSION['localpart'], ':domain_id'=>$_SESSION['domain_id']));
-    if ($usrsuccess) { $usrheaderrow = $usrheaderresult->fetch(); }
+  if (isset($_SESSION['domain_id'])) { // Check if accound or domain haven't been disabled
+    $headerquery = "SELECT domains.enabled AS domain, users.enabled AS user FROM users,domains
+                    WHERE users.localpart=:localpart AND domains.domain_id=:domain_id AND users.domain_id=domains.domain_id;";
+    $headerresult = $dbh->prepare($headerquery);
+    $headersuccess = $headerresult->execute(array(':localpart'=>$_SESSION['localpart'], ':domain_id'=>$_SESSION['domain_id']));
+    if ($headersuccess) {
+      $headerrow = $headerresult->fetch();
```
Comment (rimas-kudelis) [inline vexim/config/header.php]: Hm, what happens if `$headersuccess` or `$headerrow` is false for some reason?

File: vexim/config/header.php [hunk 4]
```diff
@@ -1,26 +1,27 @@
...
-  if (isset($_SESSION['domain_id'])) {
-    $domheaderquery = "SELECT enabled FROM domains WHERE domains.domain_id=:domain_id";
-    $domheaderresult = $dbh->prepare($domheaderquery);
-    $domsuccess = $domheaderresult->execute(array(':domain_id'=>$_SESSION['domain_id']));
-    if ($domsuccess) { $domheaderrow = $domheaderresult->fetch(); }
-    $usrheaderquery = "SELECT enabled FROM users WHERE localpart=:localpart AND domain_id=:domain_id";
-    $usrheaderresult = $dbh->prepare($usrheaderquery);
-    $usrsuccess = $usrheaderresult->execute(array(':localpart'=>$_SESSION['localpart'], ':domain_id'=>$_SESSION['domain_id']));
-    if ($usrsuccess) { $usrheaderrow = $usrheaderresult->fetch(); }
+  if (isset($_SESSION['domain_id'])) { // Check if accound or domain haven't been disabled
```
Comment (rimas-kudelis) [inline vexim/config/header.php]: This comment has two typos. :) Maybe we just don't need it?

File: vexim/config/header.php (hunk 3 above)
Comment (Udera) [inline vexim/config/header.php]: I'm not sure if I understand correctly. Do you mean we should make a query like `SELECT COUNT(*) FROM users,domains WHERE domains.enabled='1' AND users.enabled='1' AND ...` and we continue only if the query can be made and the result is `1`? For anything else we end the session?

File: vexim/config/header.php (hunk 4 above)
Comment (Udera) [inline vexim/config/header.php]: OMG, `d` and `t` are not even close on the keyboard for same lame excuse ;-)

File: vexim/config/header.php (hunk 3 above)
Comment (rimas-kudelis) [inline vexim/config/header.php]: Nah, I mean we should probably have an `if (!$headersuccess)` case to handle possible issues, and then also check if `$headerrow` is not `false` (or is an array) before using it as an array.

**Comment by Udera** [comment]
I added a verification for the database queries.

**Comment by rimas-kudelis** [comment]
Thank you!
